micronaut:
  application:
    name: micronautexp
  server:
    netty: # does this duplicate teh top level netty block?  this is from the docs
      access-logger:
        enabled: true # Enables the access logger
        logger-name: my-access-logger # A logger name, optional, default is `HTTP_ACCESS_LOGGER`
        log-format: common # A log format, optional, default is Common Log Format
netty:
  default:
    allocator:
      max-order: 3
